[build-system]
requires = [
    "setuptools>=30.3.0",
    "wheel"
]

[pytest]
python_files = [
    "test_*.py",
    "*_test.py",
    "tests.py"
]
addopts = [
    "-ra",
    "--strict-markers",
    "--tb=short",
]
testpaths = ["tests"]