name: "Publishing"
on:
  release:
    types: [published]
jobs:
  verification:
    uses: ./.github/workflows/verification.yml
  publish:
    runs-on: ubuntu-latest
    needs: verification
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
            pip install --upgrade pip
            python -mpip install --progress-bar=off -r ci/requirements.txt
            virtualenv --version
            pip --version
            nox --version
            pip list --format=freeze
      - name: Publishing
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          nox -e publish -v
